version: "3.3"
services:
  api:
    container_name: "api"
    build: .
    hostname: api
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    networks:
      - rabbitmq

networks:
  rabbitmq:
    external: true